---
# This playbook contains common plays that will be run on all nodes.
- hosts: all

  tasks:
   - name: Create a 2048-bit SSH key for user gracec in ~gracec/.ssh/id_rsa
     user:
      name: gracec
      commeny: Grace Chen
      groups: wheel
      append: yes 
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      tags: add_user 
      
   - name: Remove the user 'gracec'
     user:
      name: gracec
      state: absent
      remove: yes
      tags: delete_user
